apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingpong
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  project: default
  source:
    repoURL: https://github.com/yismaili/ping_pong
    path: k8s/manifests
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true