apiVersion: v1
kind: Secret
metadata:
  name: pingpong-secrets
  namespace: pingpong
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: MzU5MzQ0ODY5NDctaDRmazdrbTJscmM5cDZyNjRtNDJvZG1tb2lycGlzdHUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GOOGLE_CLIENT_SECRET: R09DU1BYLXc4UVNlc0ZGYWduS21NeUU4Y2VTaV9CZkJvdFU=
  JWT_SECRET: c2VjcmV0ZQ==
  INTRA_CLIENT_ID: dS1zNHQydWQtYzgxMmVmNTg2MWYwNWViY2RjZjE2NDc5NDVjNWE3YTAxNWQ2Y2ZkNDAxNTRjNTgxMDc4YTdhMWYyMThmNGEzZQ==
  INTRA_CLIENT_SECRET: cy1zNHQydWQtMWQ5ZTdjM2ExNjNlNTdkZjNhZDQ1YTE2NDYwYWIyZmY1YjkwNmIzMWVjMDU3ZjQwMGY1Mzc3YjYyNzlhZmY3Yw==
  CLOUDINARY_CLOUD_NAME: ZG95bXFweWZr
  CLOUDINARY_API_KEY: NDA4NTc4MjcxNzI1MTI3
  CLOUDINARY_API_SECRET: aXFwYUtFYXNrS2FZZWZ3RFZzTEdIRmtqRDln
  PASSWORD: cGFzczEzMzc=
  POSTGRES_PASSWORD: cGFzczEzMzc=
  PUBLIC_ID: b2x5bXBpY19mbGFn